on:
  push:
  pull_request:

name: Integration

jobs:
  coding-style:
    name: Check coding-style
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check Coding Style
        run:  check.sh $(pwd) $(pwd)
      - name: Report banana result
        run:  |
          NB_ERROR=$(cat coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            ERRORS=$(cat coding-style-reports.log);
            echo "Banana found $NB_ERROR error(s)"
            echo "$ERRORS"
            exit 1
          fi
            echo "Everything is good ! Keep on coding !"
            exit 0

  compile:
    name: Check compilation
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile Project
        run:  make

  run-tests:
    name: Run Tests
    runs-on:  ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    needs:  [compile, coding-style]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile Project
        run:  make compile_tests
      - name: Run Tests
        run:  ./unit_testing
      - name: Run Integration Tests
        run:  ./integration_testing

